### ISSUE TITLE
Support for online multiplayer

### ISSUE THREAD

**Issue by kusti420** [VarunBanka/tic_tac_toe_using_python#1]

**Comment by VarunBanka** [comment]
sure, this feature will be available the next update.
we appreciate your valuable suggestion.
thanks and regards.

**Comment by VarunBanka** [comment]
hiiii, how to make it online ? bcs html scripts isnt working

**Comment by kusti420** [comment]
gotta make 2 scripts for both hosting a server and a client, dont worry about the graphics, could do that when you could even establish a connection between server and 2 clients

**Comment by VarunBanka** [comment]
> gotta make 2 scripts for both hosting a server and a client, dont worry about the graphics, could do that when you could even establish a connection between server and 2 clients

so for this i have to get a domain and server ?

**Comment by kusti420** [comment]
> > gotta make 2 scripts for both hosting a server and a client, dont worry about the graphics, could do that when you could even establish a connection between server and 2 clients
> 
> so for this i have to get a domain and server ?

no u dont need a domain, u could just use ur ip, and u gotta host a server, u could theoretically host it yourself

**Comment by VarunBanka** [comment]
Done

**Comment by kusti420** [comment]
ill try it out once i get home
